# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5f6913a798324e911d2f4d157ab97f5e093cf068015ac680295c0de2c170cf3f6582c35a85e386797e5fda23bf8d383119dc4086deb8b8ef48cdaf2d7dee2b6

test:
  secret_key_base: e00d569293fcf6b28fe68b7640cb67c8287136dcb5d8bbb2153f68df4a64855e76faf3a8c099c4c67df972abb441608c08e9643809602de9c4bfc598f1513e0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
